name: Publish to PyPI

# Publish package to PyPI when a version tag is pushed
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual triggering

# Set permissions for trusted publishing (recommended over API tokens)
permissions:
  contents: read
  id-token: write  # For trusted publishing to PyPI

jobs:
  # Run tests before publishing
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Run tests
      run: |
        uv run pytest --cov=src --cov-report=term-missing

    - name: Run pre-commit hooks
      run: |
        uv run pre-commit run --all-files

  # Build and publish package
  build-and-publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper versioning

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Build package
      run: |
        uv build

    - name: Verify package contents
      run: |
        uv run twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Use trusted publishing instead of API tokens (more secure)
        # Configure this in your PyPI project settings
        attestations: true
        verbose: true
